# Font Settings
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.0

# Window Layout
window_padding_width 10
background_opacity 0.90
confirm_os_window_close 0

# Materia-Dark Color Palette
foreground            #e1e1e1
background            #121212
selection_foreground  #121212
selection_background  #8ab4f8
url_color             #8ab4f8
cursor                #8ab4f8

# Colors
# Black (Dark Gray in Materia)
color0  #3c3c3c
color8  #4d4d4d
# Red
color1  #f28b82
color9  #f28b82
# Green
color2  #81c995
color10 #81c995
# Yellow
color3  #fdd663
color11 #fdd663
# Blue (Accent)
color4  #8ab4f8
color12 #8ab4f8
# Magenta
color5  #af5ed1
color13 #af5ed1
# Cyan
color6  #78d9ec
color14 #78d9ec
# White
color7  #e1e1e1
color15 #ffffff
