# Fuzzel Configuration (Materia-Dark)
font=Comfortaa:size=12
terminal=kitty
prompt="❯ "
layer=overlay

[colors]
background=121212f2
text=e1e1e1ff
match=8ab4f8ff
selection=3c3c3cff
selection-text=8ab4f8ff
selection-match=8ab4f8ff
border=8ab4f8ff

[border]
width=2
radius=6
